### ISSUE TITLE
Exhale emoji is missing 😤

### ISSUE THREAD

**Issue by TheDcoder** [rugk/awesome-emoji-picker#113]
Hi, the exhale forcefully from the nose emoji is missing from the picker, and I am mad about it 😤

**Comment by TheDcoder** [comment]
Never-mind, it somehow magically appeared on the list. I also put the emoji in the search bar just to see if exists, but there was no match. Maybe a new feature could be added where emojis can be directly searched with their character? It would help those like me who don't look properly.

**Comment by rugk** [comment]
Hi and thanks for the report.

> Hi, the exhale forcefully from the nose emoji is missing from the picker, and I am mad about it triumph

Hehe, well, I could also find it. search for "triumph", because that is how it is officially™ called:
> 😤 Face with Look of Triumph

![emooji](https://user-images.githubusercontent.com/11966684/106937152-ba2a9f00-671d-11eb-87e7-8c6e3f1eb500.png)


At least according to Unicode. See Emojipedia for details: https://emojipedia.org/face-with-steam-from-nose/

> I also put the emoji in the search bar just to see if exists, but there was no match. Maybe a new feature could be added where emojis can be directly searched with their character? It would help those like me who don't look properly.

Yes, this is a good idea that unfortunately is not possible currently, see https://github.com/rugk/awesome-emoji-picker/issues/81. There it is also described how to search Emojipedia from the address bar/add-on, where this works at least.

So as all issues seem to be resolved, I'd close this issue.

**Comment by TheDcoder** [comment]
Thank you for addressing all the points. I didn't know the extension was just a wrapper around Emoji Mart :sweat_smile:

To me it sounds trivial to make the enhancement for "reverse searching" emoji, not sure why they haven't done it yet honestly. Also thanks for the emojipedia tip.

P.S I didn't know steaming from the nose was a sign of triumph, LOL.
