### ISSUE TITLE
Thunderbird version

### ISSUE THREAD

**Issue by nclm** [rugk/awesome-emoji-picker#49]
## Background
Since Firefox and Thunderbird extensions are probably made the same way and since Thunderbird currently has a antiquated emoticon picker, it would be really nice to have a version of Awesome Emoji Picker for Thunderbird.

## Proposed solution
Insert the emoji picking window in the editing bar of the composing window, possibly replacing the current emoticon picker:

![Mockup](https://user-images.githubusercontent.com/923008/59565225-c3e72680-9050-11e9-8a24-0a81bf2fd70b.png)

Distribute it on https://addons.thunderbird.net

**Comment by rugk** [comment]
Yeah, I need to look into it (whether Thunderbird supports WebExtensions)…

**Comment by tdulcet** [comment]
Thunderbird does support WebExtensions: https://thunderbird-webextensions.readthedocs.io/en/latest/

**Comment by rugk** [comment]
Thanks for the pointer. That's great to hear, but it needs to be looked into whether it can be made compatible/needs adjustments.

**Comment by tdulcet** [comment]
I just filed a bunch of bugs with Thunderbird that would need to be fixed to get the Awesome Emoji Picker fully working:

- https://bugzilla.mozilla.org/show_bug.cgi?id=1641573
- https://bugzilla.mozilla.org/show_bug.cgi?id=1641575
- https://bugzilla.mozilla.org/show_bug.cgi?id=1641576
- https://bugzilla.mozilla.org/show_bug.cgi?id=1641577
- https://bugzilla.mozilla.org/show_bug.cgi?id=1641580

and this would make debugging easier:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1641574

Even with these bugs/missing features, I was able to get the emoji picker and autocorrect (#93) to work in Thunderbird's compose window with very minimal changes.

**Comment by rugk** [comment]
Wow thanks. Good work! :smiley:

**Comment by rugk** [comment]
[Issue #1641577](https://bugzilla.mozilla.org/show_bug.cgi?id=1641577#c16) has a workaround posted, does this fix the problem, @tdulcet?
If so, I've converted your list above to a checklist, so let's tick the issues that are solved…

**Comment by tdulcet** [comment]
> [Issue #1641577](https://bugzilla.mozilla.org/show_bug.cgi?id=1641577#c16) has a workaround posted, does this fix the problem

No. With the workaround, the options page will load, but changing the options has no effect.

> If so, I've converted your list above to a checklist, so let's tick the issues that are solved…

OK, I marked the bugs that have been fixed. At a minimum, we only need 1641577 and 1641573 to be fixed to get this working. The rest either are missing features (1641575 and 1641576) or will eliminate Thunderbird specific code that is currently required (1641580).

As soon as #93 is merged, I will create a PR for this, so that people can test it out. Note that Thunderbird 78, the next major version, is currently scheduled for [release on July 17](https://www-stage.thunderbird.net/en-US/thunderbird/78.0/releasenotes/). Thunderbird follows the Firefox ESR release schedule, so there is only a major release every year.

**Comment by tdulcet** [comment]
Bug 1641577 has finally been fixed, which was the last blocking bug (see https://github.com/rugk/awesome-emoji-picker/issues/49#issuecomment-635390352)! Unfortunately, they will not uplift the fix to the current Thunderbird 78 release, but it is now available in Thunderbird Beta and will be available in the next major version, Thunderbird 91, which is currently scheduled for [release on July 13](https://wiki.mozilla.org/Release_Management/Calendar).

**Comment by tdulcet** [comment]
@rugk and I published an experimental version of the Awesome Emoji Picker for Thunderbird: https://addons.thunderbird.net/en-US/thunderbird/addon/awesome-emoji-picker/. It requires Thunderbird 91, which was just released last week. Feedback is welcome.

It includes the emoji autocorrect feature from #93, as well as a context menu item to fix #45. Note that the emoji picker and emoji autocorrect feature currently only work in the message body of the compose window.

**Comment by dvergeylen** [comment]
I've tested with Thunderbird 91.1.0, under Debian Testing Wayland.

I'm experiencing a weird flickering of the menu when clicking on it. Does not appear 100% of the time, I'd say roughly 90%.

https://user-images.githubusercontent.com/8804879/132873574-00d938b6-f5dc-476d-a0e3-bf2ca9808448.mp4


That might not be related to the addon at all (which I extensively use with Firefox 🙏).

**Comment by rugk** [comment]
Oh go0sh, this looks like some (P)ReactJS rendering issue or whatever… Does it matter, where on the screen you place the window before opening the popup?

Because in your video/GIF (thanks BTW for that, this is very helpful!) I can see it that the height you have available is not much, the popup just fits on the screen.
So maybe move the window up a bit and then the popup has enough space to be shown? (I'm just speculating here…)

**Comment by dvergeylen** [comment]
>Does it matter, where on the screen you place the window before opening the popup?

It doesn't, but that might be a hint: whatever the window position and size, the menu tries to get as much height as it can (resulting in too big emojis, proportionally with the rest of the interface) until it collides with the bottom of the screen. I guess it can't find a correct "non colliding" position and starts flickering by repositioning itself again and again... 🤔

I don't experience the issue in Firefox 91.1.0esr.

Hope this helps!

**Comment by rugk** [comment]
Given the same engine etc. should be underlying Firefox and Thunderbird, maybe we should consider opening a Thunderbird bug for that? Or do you have any other ideas, @tdulcet?

**Comment by tdulcet** [comment]
> Given the same engine etc. should be underlying Firefox and Thunderbird, maybe we should consider opening a Thunderbird bug for that? Or do you have any other ideas, @tdulcet?

No, I definitely agree that someone should create a bug on BMO with the above video, as this is most likely a Thunderbird/Gecko issue since the whole popup flickers/flashes.

@dvergeylen - Thanks for reporting this! I noticed in your video that there is another format toolbar icon for a different add-on. Do you have any issues with the popup for that? I agree that the popup in your video is a little bigger than I would expect:
![image](https://user-images.githubusercontent.com/15305150/133882467-b89583a1-43a0-48a2-b087-f1d45cb9fe2b.png)
