### ISSUE TITLE
Could you add Waterfox support for this addon?

### ISSUE THREAD

**Issue by kazerniel** [rugk/awesome-emoji-picker#51]
This addon looks awesome, but I'm using Waterfox 56.2.12 (which the Firefox addon site seems to identify as Firefox 57.0), and it tells me that I can't install the addon below browser version v63.0 :disappointed:

**Comment by rugk** [comment]
No, not yet, because [this addons needs to use Web Components and these are only supported in Firefox >= 63](https://developer.mozilla.org/en-US/docs/Web/Web_Components#Browser_compatibility).
Assuming Waterfox follows the same versioning scheme and this is the lastest version, there is nothing I can do.

Please correct me, if I am wrong.
