### ISSUE TITLE
The automatic system dark mode detection doesn't work with Windows 10

### ISSUE THREAD

**Issue by realpixelcode** [rugk/awesome-emoji-picker#94]
Unfortunately, the addon doesn't recognize Windows 10's dark mode 😕

**Comment by rugk** [comment]
Is https://stuffandnonsense.co.uk/blog/redesigning-your-product-and-website-for-dark-mode displayed in dark, when you access it? See the screenshot there for comparison. (or other sites/add-ons that use the dark mode)

If not, this is not a problem of this extension.
And I doubt it has anything to do with using Windows. Maybe you have privacy add-ons or so that e.g. set `privacy.resistFingerprinting` in `about:config` in Firefox to `true`? It is a that this disables the dark mode detection for the whole Firefox.

**Comment by realpixelcode** [comment]
Well, I think Firefox doesn't report Windows' dark mode settings at all. That's why I use your Dark Website Forcer. A solution would be to create the option of manually activating Awesome Emoji Picker's dark mode.

**Comment by rugk** [comment]
Nope: Firefox should support that: https://www.ghacks.net/2018/07/13/firefox-will-support-windows-10s-dark-mode/

There has to be something wrong with your setup/browser.

**Comment by realpixelcode** [comment]
Then Firefox' privacy settings and my adblockers are probably the problem. Nonetheless, manual dark mode activation would be awesome 😊

**Comment by rugk** [comment]
So could you solve your specific issue?
(Adblockers also should/cannot interfere with other add-on's, so this is no problem. They could only change your Firefox settings.)

I do not consider a manual dark mode activation useful to implement just for some edge cases like this, in which somewhat is causing a browser functionality not to work.
As stated, the issue can likely be solved by some configuration work.
Thus, unfortunately, I have to close this issue.

If anyone still experiences this issue, please check your `privacy.resistFingerprinting` setting and disable it.
