### ISSUE TITLE
Mixed emojis

### ISSUE THREAD

**Issue by AXeL-dev** [rugk/awesome-emoji-picker#97]
## Bug description
I noticed that some emojis were displayed over each others (check the screenshot below), but i'm not sure if this is really a bug or maybe something else.

![image](https://user-images.githubusercontent.com/30635693/84090486-e0126f00-a9e9-11ea-946e-271932078a5d.png)

## System
Operating system and version: Linux (Ubuntu 18.04)
Browser and version: Firefox (Latest)
Add-on version: Latest

**Comment by rugk** [comment]
Which emoji style do you use? "native" I guess?

If so these are [emojis that are combined using a ZWJ](https://emojipedia.org/zero-width-joiner/). If the font/emoji set you use does not support these emojis, it will display them as two emojis.

This then results in an overflow.

So the underlying error is totally technical here and cannot really be solved by us… :thinking: 
Or do you have an idea how?

Also, this likely also [happens in our upstream library](https://missive.github.io/emoji-mart/), does not it?
If so, it's possibly also an issue [for them](https://github.com/missive/emoji-mart) in general…

**Workaround:** (for now) use/choose a different emoji set in the settings

**Comment by rugk** [comment]
oh BTW, I can reproduce it with Firefox 77 and Fedora 32, so an upgrade won't help. (It looks a little better here for me with a slightly bigger emoji size though)

![emojiOverflow](https://user-images.githubusercontent.com/11966684/84121300-440f5480-aa37-11ea-91f0-892fbb935113.png)

An emoji affacted is e.g. the **person** cook 🧑‍🍳, i.e. the gender-neutral emojis of 👨‍🍳 & 👩‍🍳. See https://emojipedia.org/cook/. It has been introduced in Emoji 12.1, so apparently Firefox does not support that version yet.
I guess that is likely already known/reported, but I could not find a new Firefox bugzilla bug, so I've opened https://bugzilla.mozilla.org/show_bug.cgi?id=1644346.

**Comment by AXeL-dev** [comment]
Okay, thank you, i have a better understanding now about the source of the issue :+1:

**Comment by rugk** [comment]
Well… given [the Firefox issue has been fixed in record time](https://bugzilla.mozilla.org/show_bug.cgi?id=1644346), I'll certainly leave this open until that is released or so (in Firefox 79).

Also we might think what we could do to detect/workaround these errors in the future? (as it is likely prune to reoccur) Maybe detect the emojis based on their width or so and hide them?
Though that may be a too big maintenance and potential problem burden for such an edge case workaround. It could e.g. lead to false-positives on Windows with that: https://github.com/missive/emoji-mart/issues/310.

So yeah, for now marking it as a blocked upstream (Firefox) issue.

**Comment by rugk** [comment]
Ups, accidentally closed.

Fixed in Firefox 78 [now even](https://bugzilla.mozilla.org/show_bug.cgi?id=1644346#c16), so that when Firefox 78 arrives, I'll close this one.
